"""Add tags to post

Revision ID: 6b0a2649698
Revises: 7442984227b
Create Date: 2012-10-24 17:17:32.477170

"""

# revision identifiers, used by Alembic.
revision = '6b0a2649698'
down_revision = '7442984227b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tags', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tags')
    ### end Alembic commands ###
